from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('', views.vista_inicio, name='vista_inicio'),
    path('TurnoMañana', views.vista_mañana, name='vista_mañana'),
    path('TurnoTarde', views.vista_tarde, name='vista_tarde'),
    path('Suiza', views.vista_Suiza, name='vista_Suiza'),
    path('Uzbekistán', views.vista_uzbekistan, name='vista_uzbekistan'),
    path('Afganistán', views.vista_afganistan, name='vista_afganistan'),
    path('Bélgica', views.vista_belgica, name='vista_belgica'),
    path('España', views.vista_españa, name='vista_españa'),
    path('Cuba', views.vista_cuba, name='vista_cuba'),
    path('Kuwait', views.vista_kuwait, name='vista_kuwait'),
    path('Indonesia', views.vista_indonesia, name='vista_indonesia'),
    path('Grecia', views.vista_grecia, name='vista_grecia'),
    path('Lituania', views.vista_lituania, name='vista_lituania'),
    path('Yemen', views.vista_yemen, name='vista_yemen'),
    path('Austria', views.vista_austria, name='vista_austria'),
    path('Egipto', views.vista_egipto, name='vista_egipto'),
    path('CentroAfricana', views.vista_africana, name='vista_africana'),
    path('Brunéi', views.vista_brunei, name='vista_brunei'),
    path('Guatemala', views.vista_guatemala, name='vista_guatemala'),
    path('Croacia', views.vista_croacia, name='vista_croacia'),
    path('Catar', views.vista_catar, name='vista_catar'),
    path('Turquia', views.vista_turquia, name='vista_turquia'),
    path('CaboVerde', views.vista_cabo, name='vista_cabo'),
    path('Hungria', views.vista_hungria, name='vista_hungria'),
    path('Venezuela', views.vista_venezuela, name='vista_venezuela'),
    path('CoreaDelSur', views.vista_coreadelsur, name='vista_coreadelsur'),
    path('Argentina', views.vista_argentina, name='vista_argentina'),
    path('SanMarino', views.vista_marino, name='vista_marino'),
    path('Etiopia', views.vista_etiopia, name='vista_etiopia'),
]